import type { WorkflowResourceLink } from "../../db/schema/event-workflow-task-defs.js";
import { WORKFLOW_RESOURCES } from "./workflowResources.js";

export type WorkflowPhase =
  | "upon_deposit"
  | "two_point_five_weeks"
  | "ros"
  | "three_weeks"
  | "two_weeks"
  | "one_week_before"
  | "staff_checkin_72_48h"
  | "twenty_four_h"
  | "during"
  | "post";

export type WorkflowRole = "Sales" | "Admin" | "Ops" | "Marketing" | "Event Host";

export type DueAnchor = "event_date" | "deposit_date" | "immediate";

export interface CookingTaskDefSeed {
  phase: WorkflowPhase;
  title: string;
  description?: string;
  role: WorkflowRole;
  dueOffsetDays: number;
  dueAnchor: DueAnchor;
  sortOrder: number;
  resourceLinks?: WorkflowResourceLink[];
  conditional?: Record<string, unknown>;
  traceId: string;
}

const R = WORKFLOW_RESOURCES;

/**
 * Exhaustive Cooking Family A task defs (plan 01).
 * Intake-only fields live on events schema — see cookingTraceTargets.ts.
 */
export const COOKING_TASK_DEFS: CookingTaskDefSeed[] = [
  // —— upon_deposit ——
  {
    phase: "upon_deposit",
    title: "Sales intake meeting — location, date, timing, preferences",
    role: "Sales",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 10,
    traceId: "C001",
  },
  {
    phase: "upon_deposit",
    title: "Email deposit notify to Dave, Zach, Monica, Eileen",
    description:
      "Required notify. Slack Salesalert is optional resource only — do not treat as required CRM step.",
    role: "Sales",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 20,
    resourceLinks: [R.slackSalesAlert],
    traceId: "C030",
  },
  {
    phase: "upon_deposit",
    title: "Create FareHarbor item",
    role: "Admin",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 30,
    resourceLinks: [R.fareharborHowTo],
    traceId: "C031",
  },
  {
    phase: "upon_deposit",
    title: "Create participation link (Google Sheets or Forms)",
    role: "Admin",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 40,
    traceId: "C032",
  },
  {
    phase: "upon_deposit",
    title: "Create / link Post Event Survey",
    role: "Admin",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 50,
    resourceLinks: [R.postEventSurvey],
    traceId: "C033",
  },
  {
    phase: "upon_deposit",
    title: "Set CRM workflow direct event link",
    role: "Admin",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 60,
    traceId: "C034",
  },
  {
    phase: "upon_deposit",
    title: "Create BEO (Admin)",
    description: "Admin creates the BEO artifact — distinct from Ops BEO Shell.",
    role: "Admin",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 70,
    traceId: "C035",
  },
  {
    phase: "upon_deposit",
    title: "Attach Run of Show template",
    role: "Admin",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 80,
    traceId: "C036",
  },
  {
    phase: "upon_deposit",
    title: "Create BEO Shell and link to FareHarbor",
    description: "Ops creates BEO Shell and links BEO to FareHarbor.",
    role: "Ops",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 90,
    resourceLinks: [R.beoShellHowTo],
    traceId: "C037",
  },
  {
    phase: "upon_deposit",
    title: "Reach out to Instructor and Event Team immediately",
    role: "Ops",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 100,
    traceId: "C038",
  },
  {
    phase: "upon_deposit",
    title: "Track 48h staff response; escalate if needed",
    description:
      "Individual staff have 48 hours to respond. If no response, management escalates.",
    role: "Ops",
    dueOffsetDays: 2,
    dueAnchor: "immediate",
    sortOrder: 110,
    traceId: "C039",
  },
  {
    phase: "upon_deposit",
    title: "Record which member reached out for staff availability",
    role: "Ops",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 120,
    traceId: "C040",
  },
  {
    phase: "upon_deposit",
    title: "Contact venue and reserve loading dock",
    role: "Ops",
    dueOffsetDays: 0,
    dueAnchor: "immediate",
    sortOrder: 130,
    resourceLinks: [R.vendorDirectory],
    traceId: "C041",
  },

  // —— two_point_five_weeks ——
  {
    phase: "two_point_five_weeks",
    title: "Email client 2.5 weeks before — schedule ROS",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 200,
    traceId: "C042",
  },
  {
    phase: "two_point_five_weeks",
    title: "Schedule Run of Show with client",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 210,
    traceId: "C043",
  },
  {
    phase: "two_point_five_weeks",
    title: "Send calendar invite (client + Sales)",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 220,
    traceId: "C044",
  },

  // —— ros ——
  {
    phase: "ros",
    title: "ROS — confirm menu (App / Entree / Dessert)",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 300,
    traceId: "C045",
  },
  {
    phase: "ros",
    title: "ROS — double-check bar",
    description: "Handling? Consumption? Wine or beer?",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 310,
    traceId: "C046",
  },
  {
    phase: "ros",
    title: "ROS — confirm arrival method",
    description: "Motorcoach / Uber / own / all of the above",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 320,
    traceId: "C047",
  },
  {
    phase: "ros",
    title: "ROS — confirm event time change",
    description: "Has the event time changed — yes/no; if yes, new time?",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 330,
    traceId: "C048",
  },
  {
    phase: "ros",
    title: "ROS — confirm headcount",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 340,
    traceId: "C049",
  },
  {
    phase: "ros",
    title: "ROS — capture day-of POC",
    description: "Name, email, phone",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 350,
    traceId: "C050",
  },
  {
    phase: "ros",
    title: "ROS — multimedia permission",
    description:
      "OK for marketing | OK internal only | No photos — use talk-track helper",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 360,
    traceId: "C051",
  },
  {
    phase: "ros",
    title: "ROS — seating curation",
    description: "Curate Y/N → random or client pre-organized groups",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 370,
    traceId: "C052",
  },
  {
    phase: "ros",
    title: "ROS — food addition counts",
    description:
      "Charcuterie count, additional protein, mystery ingredients, alternative sauces",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 380,
    traceId: "C053",
  },
  {
    phase: "ros",
    title: "ROS — custom add-on progress",
    description:
      "Aprons logo→embroiderist, custom name, glassware, cheeseboard, chocolate mold, chef hats, berets",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 390,
    resourceLinks: [
      R.vendorDirectory,
      R.wattzDesign,
      R.minutemanPress,
      R.basecampDc,
      R.qualityGlassEngraving,
    ],
    traceId: "C054",
  },
  {
    phase: "ros",
    title: "ROS — confirm transportation",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 400,
    resourceLinks: [R.vendorDirectory],
    conditional: { if: "transportation_needed" },
    traceId: "C055",
  },
  {
    phase: "ros",
    title: "Email BEO to all event staff + embed in FareHarbor",
    role: "Ops",
    dueOffsetDays: 17,
    dueAnchor: "event_date",
    sortOrder: 410,
    traceId: "C056",
  },

  // —— one_week_before ——
  {
    phase: "one_week_before",
    title: "Marketing — print menu / recipe cards",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 500,
    resourceLinks: [R.recipeCardsHowTo],
    traceId: "C057",
  },
  {
    phase: "one_week_before",
    title: "Marketing — chef verified menu for THIS function?",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 510,
    traceId: "C058",
  },
  {
    phase: "one_week_before",
    title: "Marketing — appropriate paper in stock?",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 520,
    traceId: "C059",
  },
  {
    phase: "one_week_before",
    title: "Marketing — printed in office? (FedEx how-to)",
    description: "Zach Finch — FedEx print how-to video when available",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 530,
    traceId: "C060",
  },
  {
    phase: "one_week_before",
    title: "Marketing — QR code created",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 540,
    resourceLinks: [R.qrCodesFolder],
    traceId: "C061",
  },
  {
    phase: "one_week_before",
    title: "Marketing — QR code on website",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 550,
    resourceLinks: [R.qrCodesFolder],
    traceId: "C062",
  },
  {
    phase: "one_week_before",
    title: "Marketing — QR code printed",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 560,
    resourceLinks: [R.qrCodesFolder],
    traceId: "C063",
  },
  {
    phase: "one_week_before",
    title: "Marketing — menu tents",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 570,
    traceId: "C064",
  },
  {
    phase: "one_week_before",
    title: "Marketing — recipe cards",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 580,
    resourceLinks: [R.recipeCardsHowTo],
    traceId: "C065",
  },
  {
    phase: "one_week_before",
    title: "Marketing — bar menu",
    role: "Marketing",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 590,
    traceId: "C066",
  },
  {
    phase: "one_week_before",
    title: "Order inventory / supplemental supplies",
    description:
      "Includes glassware, cocktail napkins, 3rd party furniture, plastic/ceramic plates, Gtown olive oil + balsamic, etc. See Inventory Links.",
    role: "Ops",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 600,
    resourceLinks: [
      R.inventoryLinks,
      R.vendorDirectory,
      R.vendorDirectoryLocal,
      R.georgetownOliveOil,
      R.qualityGlassEngraving,
      R.basecampDc,
    ],
    traceId: "C067",
  },
  {
    phase: "one_week_before",
    title: "Confirm custom aprons sent to Basecamp",
    role: "Ops",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 610,
    resourceLinks: [R.vendorDirectory, R.basecampDc],
    traceId: "C069",
  },
  {
    phase: "one_week_before",
    title: "Company aprons cleaned and ready",
    role: "Ops",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 620,
    resourceLinks: [R.vendorDirectory],
    traceId: "C090",
  },
  {
    phase: "one_week_before",
    title: "Logo’d aprons ready for Basecamp pickup",
    role: "Ops",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 630,
    resourceLinks: [R.vendorDirectory],
    traceId: "C091",
  },
  {
    phase: "one_week_before",
    title: "Pick up remaining supplies (in-person / curbside / rush)",
    description: "Method: in-person | curbside | rush shipping",
    role: "Ops",
    dueOffsetDays: 7,
    dueAnchor: "event_date",
    sortOrder: 640,
    conditional: { supplyPickupMethods: ["in_person", "curbside", "rush_shipping"] },
    traceId: "C092",
  },

  // —— staff_checkin_72_48h ——
  {
    phase: "staff_checkin_72_48h",
    title: "BEO staff check-in — Host and Instructor (72–48h)",
    description:
      "Phone Host and Instructor to discuss questions, concerns, and additional event details vs BEO/leadership.",
    role: "Ops",
    dueOffsetDays: 2,
    dueAnchor: "event_date",
    sortOrder: 700,
    traceId: "C089",
  },

  // —— twenty_four_h ——
  {
    phase: "twenty_four_h",
    title: "24h inventory triple-check (Ops Manager or Intern)",
    role: "Ops",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 800,
    conditional: { assigneeOptions: ["Ops Manager", "Intern"] },
    traceId: "C093",
  },
  {
    phase: "twenty_four_h",
    title: "Acquire ice (Y/N)",
    role: "Ops",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 810,
    conditional: { assigneeOptions: ["Ops Manager", "Intern"] },
    traceId: "C094",
  },

  // —— during ——
  {
    phase: "during",
    title: "Follow event-specific BEO for layout / inventory / client",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 900,
    resourceLinks: [R.eventPhotosDrive, R.companyHandbook],
    traceId: "C095",
  },
  {
    phase: "during",
    title: "Event Host — follow Company Handbook",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 910,
    resourceLinks: [R.companyHandbook],
    traceId: "C096",
  },
  {
    phase: "during",
    title: "Ops support — follow Company Handbook",
    role: "Ops",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 920,
    resourceLinks: [R.companyHandbook],
    traceId: "C097",
  },
  {
    phase: "during",
    title: "Event Lead stays in contact with day-of POC",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 930,
    traceId: "C098",
  },
  {
    phase: "during",
    title: "Ensure guest speakers speak",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 940,
    traceId: "C099",
  },
  {
    phase: "during",
    title: "Gather photo assets",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 950,
    resourceLinks: [R.eventPhotosDrive],
    traceId: "C100",
  },
  {
    phase: "during",
    title: "Upload assets to digital database",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 960,
    resourceLinks: [R.eventPhotosDrive],
    traceId: "C101",
  },
  {
    phase: "during",
    title: "Complete post-event survey",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 970,
    resourceLinks: [R.postEventSurvey],
    traceId: "C102",
  },
  {
    phase: "during",
    title: "Track drink consumption",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 980,
    traceId: "C103",
  },
  {
    phase: "during",
    title: "Collect WhatsApp media (manual)",
    description:
      "WhatsApp not integrated yet — task only appears when the WhatsApp feature toggle is on.",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 990,
    conditional: { if: "feature_whatsapp_media" },
    traceId: "C104",
  },
  {
    phase: "during",
    title: "Team debrief → post-event survey",
    description: "What did we do well? What do we need to improve?",
    role: "Event Host",
    dueOffsetDays: 0,
    dueAnchor: "event_date",
    sortOrder: 1000,
    resourceLinks: [R.postEventSurvey],
    traceId: "C105",
  },

  // —— post ——
  {
    phase: "post",
    title: "Admin — obtain media for post-event email",
    role: "Admin",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 1100,
    resourceLinks: [R.eventPhotosDrive],
    traceId: "C106",
  },
  {
    phase: "post",
    title: "Capture staff hours of the event",
    role: "Admin",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 1110,
    traceId: "C107",
  },
  {
    phase: "post",
    title: "Capture additional details on the event",
    role: "Admin",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 1120,
    traceId: "C108",
  },
  {
    phase: "post",
    title: "Consumption invoice",
    role: "Admin",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 1130,
    traceId: "C109",
  },
  {
    phase: "post",
    title: "Send thank-you email (V1/V2) + photo link",
    description: "Use dynamic experience name — never hardcode paint and sip for cooking.",
    role: "Sales",
    dueOffsetDays: 1,
    dueAnchor: "event_date",
    sortOrder: 1140,
    resourceLinks: [R.eventPhotosDrive],
    traceId: "C110",
  },
  {
    phase: "post",
    title: "V2 yes — event tracker + LinkedIn connect",
    role: "Sales",
    dueOffsetDays: 2,
    dueAnchor: "event_date",
    sortOrder: 1150,
    conditional: { if: "thank_you_v2_yes" },
    traceId: "C111",
  },
  {
    phase: "post",
    title: "+3 months — T-shirt size → CEO thank-you + Mangia T-shirt",
    role: "Sales",
    dueOffsetDays: 90,
    dueAnchor: "event_date",
    sortOrder: 1160,
    conditional: { if: "thank_you_v2_yes" },
    traceId: "C112",
  },
  {
    phase: "post",
    title: "Staff invoice EOM; receipts EOM or immediate",
    description:
      "Log hours and invoice at end of month. Receipts with invoice or immediately after event.",
    role: "Event Host",
    dueOffsetDays: 3,
    dueAnchor: "event_date",
    sortOrder: 1170,
    traceId: "C113",
  },
  {
    phase: "post",
    title: "Document event report (labor, venue fees, supplies)",
    role: "Admin",
    dueOffsetDays: 5,
    dueAnchor: "event_date",
    sortOrder: 1180,
    traceId: "C114",
  },
  {
    phase: "post",
    title: "EMAIL 2 — next event planned?",
    role: "Sales",
    dueOffsetDays: 2,
    dueAnchor: "event_date",
    sortOrder: 1190,
    conditional: { if: "feature_email2" },
    traceId: "C115",
  },
  {
    phase: "post",
    title: "EMAIL 2 — intro three individuals",
    description:
      "The kindest compliment we could receive is to introduce us to three individuals you think could benefit from our services?",
    role: "Sales",
    dueOffsetDays: 2,
    dueAnchor: "event_date",
    sortOrder: 1200,
    conditional: { if: "feature_email2" },
    traceId: "C116",
  },
  {
    phase: "post",
    title: "EMAIL 2 — newsletter interest",
    role: "Sales",
    dueOffsetDays: 2,
    dueAnchor: "event_date",
    sortOrder: 1210,
    conditional: { if: "feature_email2" },
    traceId: "C117",
  },
  {
    phase: "post",
    title: "Build another lead into Sales CRM (Yes/No)",
    role: "Sales",
    dueOffsetDays: 2,
    dueAnchor: "event_date",
    sortOrder: 1220,
    conditional: { if: "feature_email2" },
    traceId: "C118",
  },
];

export const COOKING_EXPERIENCE_KEY = "In-Person Cooking";
export const COOKING_DISPLAY_NAME = "In-Person Cooking Class";
