/**
 * Maps every COOKING-TRACEABILITY id to a seed target type for plan 01 acceptance.
 * field = events column / intake; task = workflow task def; resource = named URL seed.
 */
export type CookingTraceTarget =
  | { kind: "field"; path: string }
  | { kind: "task"; title: string }
  | { kind: "resource"; key: string }
  | { kind: "policy"; note: string };

export const COOKING_TRACE_TARGETS: Record<string, CookingTraceTarget> = {
  C001: { kind: "task", title: "Sales intake meeting — location, date, timing, preferences" },
  C002: { kind: "field", path: "events.startTime" },
  C003: { kind: "field", path: "events.eventDate" },
  C004: { kind: "field", path: "lead.company / eventName" },
  C005: { kind: "field", path: "events.eventType" },
  C006: { kind: "field", path: "events.pocName|pocPhone|pocEmail" },
  C007: { kind: "field", path: "events.depositAmount (Dave/Zach/Monica)" },
  C008: { kind: "field", path: "events.headcountMin|headcountMax" },
  C009: { kind: "field", path: "events.alcoholIncluded" },
  C010: { kind: "field", path: "events.barDetails.paymentMode" },
  C011: { kind: "field", path: "events.barDetails.wineBeerSoft" },
  C012: { kind: "field", path: "events.barDetails.mixedDrinks" },
  C013: { kind: "field", path: "events.isCompetition" },
  C014: { kind: "field", path: "events.dishConfiguration" },
  C015: { kind: "field", path: "events.runOfShow.menu" },
  C016: { kind: "field", path: "events.foodAdditions.charcuterie" },
  C017: { kind: "field", path: "events.foodAdditions.additionalProtein" },
  C018: { kind: "field", path: "events.foodAdditions.mysteryIngredients" },
  C019: { kind: "field", path: "events.foodAdditions.alternativeSauces" },
  C020: { kind: "field", path: "events.foodAdditions.flavorsOfDcWarmMeal" },
  C021: { kind: "field", path: "events.customAddons.embroideredAprons" },
  C022: { kind: "field", path: "events.customAddons.engravedGlassware" },
  C023: { kind: "field", path: "events.customAddons.cheeseboard" },
  C024: { kind: "field", path: "events.customAddons.chocolateMold" },
  C025: { kind: "field", path: "events.customAddons.chefHats" },
  C026: { kind: "field", path: "events.customAddons.berets" },
  C027: { kind: "field", path: "events.transportationNeeded|transportationDetails" },
  C028: { kind: "field", path: "events.venueMode|venueRestrictions" },
  C029: { kind: "field", path: "events.venue" },
  C030: {
    kind: "policy",
    note: "Email blast Dave/Zach/Monica/Eileen; Slack optional resource only",
  },
  C031: { kind: "task", title: "Create FareHarbor item" },
  C032: { kind: "field", path: "events.participationListUrl|participationListType" },
  C033: { kind: "field", path: "events.postEventSurveyUrl" },
  C034: { kind: "field", path: "events.workflowCrmUrl" },
  C035: { kind: "task", title: "Create BEO (Admin)" },
  C036: { kind: "task", title: "Attach Run of Show template" },
  C037: { kind: "task", title: "Create BEO Shell and link to FareHarbor" },
  C038: { kind: "task", title: "Reach out to Instructor and Event Team immediately" },
  C039: { kind: "task", title: "Track 48h staff response; escalate if needed" },
  C040: { kind: "task", title: "Record which member reached out for staff availability" },
  C041: { kind: "task", title: "Contact venue and reserve loading dock" },
  C042: { kind: "task", title: "Email client 2.5 weeks before — schedule ROS" },
  C043: { kind: "task", title: "Schedule Run of Show with client" },
  C044: { kind: "task", title: "Send calendar invite (client + Sales)" },
  C045: { kind: "task", title: "ROS — confirm menu (App / Entree / Dessert)" },
  C046: { kind: "task", title: "ROS — double-check bar" },
  C047: { kind: "task", title: "ROS — confirm arrival method" },
  C048: { kind: "task", title: "ROS — confirm event time change" },
  C049: { kind: "task", title: "ROS — confirm headcount" },
  C050: { kind: "task", title: "ROS — capture day-of POC" },
  C051: { kind: "task", title: "ROS — multimedia permission" },
  C052: { kind: "task", title: "ROS — seating curation" },
  C053: { kind: "task", title: "ROS — food addition counts" },
  C054: { kind: "task", title: "ROS — custom add-on progress" },
  C055: { kind: "task", title: "ROS — confirm transportation" },
  C056: { kind: "task", title: "Email BEO to all event staff + embed in FareHarbor" },
  C057: { kind: "task", title: "Marketing — print menu / recipe cards" },
  C058: { kind: "task", title: "Marketing — chef verified menu for THIS function?" },
  C059: { kind: "task", title: "Marketing — appropriate paper in stock?" },
  C060: { kind: "task", title: "Marketing — printed in office? (FedEx how-to)" },
  C061: { kind: "task", title: "Marketing — QR code created" },
  C062: { kind: "task", title: "Marketing — QR code on website" },
  C063: { kind: "task", title: "Marketing — QR code printed" },
  C064: { kind: "task", title: "Marketing — menu tents" },
  C065: { kind: "task", title: "Marketing — recipe cards" },
  C066: { kind: "task", title: "Marketing — bar menu" },
  C067: { kind: "task", title: "Order inventory / supplemental supplies" },
  C068: { kind: "resource", key: "vendorDirectory" },
  C069: { kind: "task", title: "Confirm custom aprons sent to Basecamp" },
  C070: { kind: "resource", key: "inventoryLinks" },
  C071: { kind: "resource", key: "inventoryLinks" },
  C072: { kind: "resource", key: "inventoryLinks" },
  C073: { kind: "resource", key: "inventoryLinks" },
  C074: { kind: "resource", key: "inventoryLinks" },
  C075: { kind: "resource", key: "inventoryLinks" },
  C076: { kind: "resource", key: "inventoryLinks" },
  C077: { kind: "resource", key: "inventoryLinks" },
  C078: { kind: "resource", key: "inventoryLinks" },
  C079: { kind: "resource", key: "inventoryLinks" },
  C080: { kind: "resource", key: "inventoryLinks" },
  C081: { kind: "resource", key: "inventoryLinks" },
  C082: { kind: "resource", key: "inventoryLinks" },
  C083: { kind: "resource", key: "inventoryLinks" },
  C084: { kind: "resource", key: "inventoryLinks" },
  C085: { kind: "resource", key: "inventoryLinks" },
  C086: { kind: "resource", key: "inventoryLinks" },
  C087: { kind: "resource", key: "inventoryLinks" },
  C088: { kind: "resource", key: "inventoryLinks" },
  C089: { kind: "task", title: "BEO staff check-in — Host and Instructor (72–48h)" },
  C090: { kind: "task", title: "Company aprons cleaned and ready" },
  C091: { kind: "task", title: "Logo’d aprons ready for Basecamp pickup" },
  C092: { kind: "task", title: "Pick up remaining supplies (in-person / curbside / rush)" },
  C093: { kind: "task", title: "24h inventory triple-check (Ops Manager or Intern)" },
  C094: { kind: "task", title: "Acquire ice (Y/N)" },
  C095: { kind: "task", title: "Follow event-specific BEO for layout / inventory / client" },
  C096: { kind: "task", title: "Event Host — follow Company Handbook" },
  C097: { kind: "task", title: "Ops support — follow Company Handbook" },
  C098: { kind: "task", title: "Event Lead stays in contact with day-of POC" },
  C099: { kind: "task", title: "Ensure guest speakers speak" },
  C100: { kind: "task", title: "Gather photo assets" },
  C101: { kind: "task", title: "Upload assets to digital database" },
  C102: { kind: "task", title: "Complete post-event survey" },
  C103: { kind: "task", title: "Track drink consumption" },
  C104: { kind: "task", title: "Collect WhatsApp media (manual)" },
  C105: { kind: "task", title: "Team debrief → post-event survey" },
  C106: { kind: "task", title: "Admin — obtain media for post-event email" },
  C107: { kind: "field", path: "events.staffHoursNotes" },
  C108: { kind: "field", path: "events.additionalEventDetails" },
  C109: { kind: "task", title: "Consumption invoice" },
  C110: { kind: "task", title: "Send thank-you email (V1/V2) + photo link" },
  C111: { kind: "task", title: "V2 yes — event tracker + LinkedIn connect" },
  C112: { kind: "task", title: "+3 months — T-shirt size → CEO thank-you + Mangia T-shirt" },
  C113: { kind: "task", title: "Staff invoice EOM; receipts EOM or immediate" },
  C114: { kind: "field", path: "events.laborCost|venueFees|suppliesCost" },
  C115: { kind: "task", title: "EMAIL 2 — next event planned?" },
  C116: { kind: "task", title: "EMAIL 2 — intro three individuals" },
  C117: { kind: "task", title: "EMAIL 2 — newsletter interest" },
  C118: { kind: "task", title: "Build another lead into Sales CRM (Yes/No)" },
};

export function assertCookingTraceCoverage(): void {
  for (let i = 1; i <= 118; i++) {
    const id = `C${String(i).padStart(3, "0")}`;
    if (!COOKING_TRACE_TARGETS[id]) {
      throw new Error(`Missing COOKING_TRACE_TARGETS for ${id}`);
    }
  }
}
