services:
  app:
    build: .
    container_name: mangia_app
    restart: unless-stopped
    env_file: .env
    networks:
      - db_network    # Can talk to central_db
      - caddy_network # Can be seen by central_caddy

networks:
  db_network:
    external: true
  caddy_network:
    external: true