import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Loader2, FileText, Clock, User as UserIcon, ExternalLink } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import EmailBodyRenderer from '@/components/email/EmailBodyRenderer';

// Renders the contents of a Gmail DRAFT (the AI-generated survey email).
// Drafts use a different Gmail endpoint than messages, so we hit getDraftDetail.
export default function AILogDraftModal({ draftId, log, onClose }) {
  const { data: emailDetail, isLoading, error } = useQuery({
    queryKey: ['draft-detail', draftId],
    queryFn: async () => {
      const res = await base44.functions.invoke('getDraftDetail', { draftId });
      return res.data?.email;
    },
    enabled: !!draftId
  });

  const formatDate = (dateStr) => {
    if (!dateStr) return '';
    try { return new Date(dateStr).toLocaleString(); } catch { return dateStr; }
  };

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold text-[#C84B31] pr-6 flex items-center gap-2">
            <FileText className="w-5 h-5" />
            AI-Generated Draft
          </DialogTitle>
        </DialogHeader>

        <div className="flex flex-wrap gap-2 text-xs text-gray-600 -mt-2 mb-2">
          <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200">
            Generated by {log?.user_name || 'AI'}
          </Badge>
          {log?.details?.reason && (
            <Badge variant="outline" className="bg-gray-50">
              Trigger: {log.details.reason.replace(/_/g, ' ')}
            </Badge>
          )}
          {log?.details?.proposed_meeting_time_et && (
            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
              Proposed: {log.details.proposed_meeting_time_et}
            </Badge>
          )}
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="w-6 h-6 animate-spin text-[#C84B31]" />
          </div>
        ) : error ? (
          <div className="text-center py-6 text-sm text-red-600">
            Failed to load draft. It may have been sent or deleted from Gmail.
          </div>
        ) : !emailDetail ? (
          <div className="text-center py-6 text-sm text-gray-500">No draft data.</div>
        ) : (
          <div className="space-y-4">
            <div className="bg-gray-50 rounded-lg p-4 text-sm">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-full bg-[#C84B31]/10 flex items-center justify-center flex-shrink-0">
                  <UserIcon className="w-5 h-5 text-[#C84B31]" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-semibold text-gray-900">{emailDetail.subject || '(No Subject)'}</p>
                  <p className="text-xs text-gray-500 mt-0.5">To: {emailDetail.to || log?.details?.recipient}</p>
                  {emailDetail.date && (
                    <div className="flex items-center gap-1 mt-1 text-xs text-gray-500">
                      <Clock className="w-3 h-3" />
                      {formatDate(emailDetail.date)}
                    </div>
                  )}
                </div>
              </div>
            </div>

            <div className="border rounded-lg bg-white overflow-hidden">
              <EmailBodyRenderer content={emailDetail.body} mimeType={emailDetail.bodyMimeType} />
            </div>

            <div className="flex justify-end">
              <a
                href="https://mail.google.com/mail/u/0/#drafts"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Button variant="outline" size="sm">
                  Open in Gmail Drafts <ExternalLink className="w-3 h-3 ml-2" />
                </Button>
              </a>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}