import {
  boolean,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { clients } from "./clients.js";
import { eventTemplates } from "./event-templates.js";
import { eventWorkflowTemplates } from "./event-workflow-templates.js";
import { instructors } from "./instructors.js";
import { leads } from "./leads.js";
import { users } from "./users.js";
import { createdBy, createdDate, updatedDate } from "./metadata.js";
import {
  alcoholPreferenceEnum,
  eventDeliveryFormatEnum,
  eventStageEnum,
  eventTypeEnum,
  inventoryStatusEnum,
  invoiceStatusEnum,
  participationListTypeEnum,
  satisfactionRatingEnum,
  shippingTypeEnum,
  venueModeEnum,
} from "./enums.js";

export const events = pgTable("events", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
  eventName: varchar("event_name", { length: 255 }).notNull(),
  eventType: eventTypeEnum("event_type").notNull(),
  eventFormat: eventDeliveryFormatEnum("event_format"),
  templateId: uuid("template_id").references(() => eventTemplates.id, {
    onDelete: "set null",
  }),
  workflowTemplateId: uuid("workflow_template_id").references(
    () => eventWorkflowTemplates.id,
    { onDelete: "set null" }
  ),
  venue: varchar("venue", { length: 255 }),
  venueMode: venueModeEnum("venue_mode"),
  virtualPlatform: varchar("virtual_platform", { length: 255 }),
  venueRestrictions: text("venue_restrictions"),
  eventDate: timestamp("event_date", { withTimezone: true }).notNull(),
  startTime: varchar("start_time", { length: 50 }),
  depositReceived: boolean("deposit_received").default(false),
  depositAmount: real("deposit_amount"),
  depositReceivedAt: timestamp("deposit_received_at", { withTimezone: true }),
  depositIntakeCompletedAt: timestamp("deposit_intake_completed_at", {
    withTimezone: true,
  }),
  headcount: integer("headcount"),
  headcountMin: integer("headcount_min"),
  headcountMax: integer("headcount_max"),
  alcoholIncluded: boolean("alcohol_included").default(false),
  alcoholPreference: alcoholPreferenceEnum("alcohol_preference"),
  isCompetition: boolean("is_competition").default(false),
  dishConfiguration: varchar("dish_configuration", { length: 100 }),
  foodAdditions: jsonb("food_additions"),
  barDetails: jsonb("bar_details"),
  transportationNeeded: boolean("transportation_needed").default(false),
  transportationDetails: jsonb("transportation_details"),
  customAddons: jsonb("custom_addons"),
  mediaPermission: varchar("media_permission", { length: 100 }),
  seatingCurated: boolean("seating_curated"),
  seatingStyle: varchar("seating_style", { length: 100 }),
  runOfShow: jsonb("run_of_show"),
  /** Plan 06 — thank-you V1/V2, EMAIL 2 answers, t-shirt, LinkedIn, etc. */
  postEvent: jsonb("post_event"),
  participationListUrl: text("participation_list_url"),
  participationListType: participationListTypeEnum("participation_list_type"),
  postEventSurveyUrl: text("post_event_survey_url"),
  workflowCrmUrl: text("workflow_crm_url"),
  beoUrl: text("beo_url"),
  beoShellUrl: text("beo_shell_url"),
  /** In-app Admin BEO HTML (WYSIWYG). Distinct from external beoUrl. */
  beoDocumentHtml: text("beo_document_html"),
  beoDocumentUpdatedAt: timestamp("beo_document_updated_at", {
    withTimezone: true,
  }),
  dietaryRestrictions: text("dietary_restrictions"),
  specialRequests: text("special_requests"),
  accessibilityNeeds: text("accessibility_needs"),
  shippingRequired: boolean("shipping_required").default(false),
  shippingType: shippingTypeEnum("shipping_type"),
  shippingTracking: varchar("shipping_tracking", { length: 255 }),
  menu: text("menu"),
  pocName: varchar("poc_name", { length: 255 }),
  pocTitle: varchar("poc_title", { length: 255 }),
  pocEmail: varchar("poc_email", { length: 255 }),
  pocPhone: varchar("poc_phone", { length: 50 }),
  pocVerified: boolean("poc_verified").default(false),
  dayOfPocName: varchar("day_of_poc_name", { length: 255 }),
  dayOfPocEmail: varchar("day_of_poc_email", { length: 255 }),
  dayOfPocPhone: varchar("day_of_poc_phone", { length: 50 }),
  instructorAssigned: uuid("instructor_assigned").references(() => users.id, {
    onDelete: "set null",
  }),
  /** Instructor bio catalog entry rendered into the BEO. */
  instructorId: uuid("instructor_id").references(() => instructors.id, {
    onDelete: "set null",
  }),
  opsSupportAssigned: uuid("ops_support_assigned").references(() => users.id, {
    onDelete: "set null",
  }),
  beoLink: text("beo_link"),
  fareharborLink: text("fareharbor_link"),
  inventoryStatus: inventoryStatusEnum("inventory_status").default("Not Started"),
  loadingDockReserved: boolean("loading_dock_reserved").default(false),
  venueReservationsConfirmed: boolean("venue_reservations_confirmed").default(false),
  staffAssigned: jsonb("staff_assigned"),
  staffConfirmedDate: timestamp("staff_confirmed_date", { withTimezone: true }),
  stage: eventStageEnum("stage").default("Deposit Received"),
  driveFolderId: varchar("drive_folder_id", { length: 255 }),
  driveFolderUrl: text("drive_folder_url"),
  photosUploaded: boolean("photos_uploaded").default(false),
  followupEmailSent: boolean("followup_email_sent").default(false),
  referralRequested: boolean("referral_requested").default(false),
  linkedinConnectionSent: boolean("linkedin_connection_sent").default(false),
  postEventFeedback: text("post_event_feedback"),
  staffHoursNotes: text("staff_hours_notes"),
  additionalEventDetails: text("additional_event_details"),
  invoiceStatus: invoiceStatusEnum("invoice_status").default("Not Sent"),
  totalCost: real("total_cost"),
  laborCost: real("labor_cost"),
  suppliesCost: real("supplies_cost"),
  venueFees: real("venue_fees"),
  clientId: uuid("client_id").references(() => clients.id, { onDelete: "set null" }),
  cancellationReason: text("cancellation_reason"),
  wentToCompetitor: varchar("went_to_competitor", { length: 255 }),
  budgetIssue: boolean("budget_issue").default(false),
  timingIssue: boolean("timing_issue").default(false),
  satisfactionRating: satisfactionRatingEnum("satisfaction_rating"),
  sourceLeadId: uuid("source_lead_id").references(() => leads.id, { onDelete: "set null" }),
  createdDate: createdDate(),
  updatedDate: updatedDate(),
  createdBy: createdBy(),
});
