import {
  boolean,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { clients } from "./clients.js";
import { eventTemplates } from "./event-templates.js";
import { leads } from "./leads.js";
import { users } from "./users.js";
import { createdBy, createdDate, updatedDate } from "./metadata.js";
import {
  alcoholPreferenceEnum,
  eventDeliveryFormatEnum,
  eventStageEnum,
  eventTypeEnum,
  inventoryStatusEnum,
  invoiceStatusEnum,
  satisfactionRatingEnum,
  shippingTypeEnum,
} from "./enums.js";

export const events = pgTable("events", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
  eventName: varchar("event_name", { length: 255 }).notNull(),
  eventType: eventTypeEnum("event_type").notNull(),
  eventFormat: eventDeliveryFormatEnum("event_format"),
  templateId: uuid("template_id").references(() => eventTemplates.id, {
    onDelete: "set null",
  }),
  venue: varchar("venue", { length: 255 }),
  virtualPlatform: varchar("virtual_platform", { length: 255 }),
  venueRestrictions: text("venue_restrictions"),
  eventDate: timestamp("event_date", { withTimezone: true }).notNull(),
  depositReceived: boolean("deposit_received").default(false),
  depositAmount: real("deposit_amount"),
  headcount: integer("headcount"),
  alcoholIncluded: boolean("alcohol_included").default(false),
  alcoholPreference: alcoholPreferenceEnum("alcohol_preference"),
  transportationNeeded: boolean("transportation_needed").default(false),
  transportationDetails: jsonb("transportation_details"),
  customAddons: jsonb("custom_addons"),
  dietaryRestrictions: text("dietary_restrictions"),
  specialRequests: text("special_requests"),
  accessibilityNeeds: text("accessibility_needs"),
  shippingRequired: boolean("shipping_required").default(false),
  shippingType: shippingTypeEnum("shipping_type"),
  shippingTracking: varchar("shipping_tracking", { length: 255 }),
  menu: text("menu"),
  pocName: varchar("poc_name", { length: 255 }),
  pocTitle: varchar("poc_title", { length: 255 }),
  pocEmail: varchar("poc_email", { length: 255 }),
  pocPhone: varchar("poc_phone", { length: 50 }),
  pocVerified: boolean("poc_verified").default(false),
  instructorAssigned: uuid("instructor_assigned").references(() => users.id, {
    onDelete: "set null",
  }),
  opsSupportAssigned: uuid("ops_support_assigned").references(() => users.id, {
    onDelete: "set null",
  }),
  beoLink: text("beo_link"),
  fareharborLink: text("fareharbor_link"),
  inventoryStatus: inventoryStatusEnum("inventory_status").default("Not Started"),
  loadingDockReserved: boolean("loading_dock_reserved").default(false),
  venueReservationsConfirmed: boolean("venue_reservations_confirmed").default(false),
  staffAssigned: jsonb("staff_assigned"),
  staffConfirmedDate: timestamp("staff_confirmed_date", { withTimezone: true }),
  stage: eventStageEnum("stage").default("Deposit Received"),
  driveFolderId: varchar("drive_folder_id", { length: 255 }),
  driveFolderUrl: text("drive_folder_url"),
  photosUploaded: boolean("photos_uploaded").default(false),
  followupEmailSent: boolean("followup_email_sent").default(false),
  referralRequested: boolean("referral_requested").default(false),
  linkedinConnectionSent: boolean("linkedin_connection_sent").default(false),
  postEventFeedback: text("post_event_feedback"),
  invoiceStatus: invoiceStatusEnum("invoice_status").default("Not Sent"),
  totalCost: real("total_cost"),
  laborCost: real("labor_cost"),
  suppliesCost: real("supplies_cost"),
  venueFees: real("venue_fees"),
  clientId: uuid("client_id").references(() => clients.id, { onDelete: "set null" }),
  cancellationReason: text("cancellation_reason"),
  wentToCompetitor: varchar("went_to_competitor", { length: 255 }),
  budgetIssue: boolean("budget_issue").default(false),
  timingIssue: boolean("timing_issue").default(false),
  satisfactionRating: satisfactionRatingEnum("satisfaction_rating"),
  sourceLeadId: uuid("source_lead_id").references(() => leads.id, { onDelete: "set null" }),
  createdDate: createdDate(),
  updatedDate: updatedDate(),
  createdBy: createdBy(),
});
