import {
  boolean,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { clients } from "./clients.js";
import { users } from "./users.js";
import { createdBy, createdDate, updatedDate } from "./metadata.js";
import {
  aiFlagCategoryEnum,
  channelEnum,
  clientTypeEnum,
  eventFormatEnum,
  inquiryTypeEnum,
  leadSourceEnum,
  priorityTagEnum,
  referralSourceEnum,
  venueModeEnum,
} from "./enums.js";

export const leads = pgTable("leads", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  title: varchar("title", { length: 255 }),
  company: varchar("company", { length: 255 }),
  email: varchar("email", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 50 }),
  additionalContacts: jsonb("additional_contacts"),
  source: leadSourceEnum("source"),
  referralSource: referralSourceEnum("referral_source"),
  referralSourceOther: varchar("referral_source_other", { length: 255 }),
  inquiryType: inquiryTypeEnum("inquiry_type").default("Unknown"),
  channel: channelEnum("channel"),
  clientType: clientTypeEnum("client_type").default("New"),
  isPriority: boolean("is_priority").default(false),
  reviewed: boolean("reviewed"),
  headcountEstimate: real("headcount_estimate"),
  eventTypeInterest: varchar("event_type_interest", { length: 255 }),
  eventFormat: eventFormatEnum("event_format"),
  preferredDate: timestamp("preferred_date", { withTimezone: true }),
  meetingDate: timestamp("meeting_date", { withTimezone: true }),
  proposedMeetingDate: timestamp("proposed_meeting_date", { withTimezone: true }),
  awaitingMeetingConfirmation: boolean("awaiting_meeting_confirmation").default(false),
  surveySent: boolean("survey_sent").default(false),
  surveySentDate: timestamp("survey_sent_date", { withTimezone: true }),
  surveyResponded: boolean("survey_responded").default(false),
  stage: varchar("stage", { length: 255 }).default("New Inquiry"),
  assignedSalesRep: uuid("assigned_sales_rep").references(() => users.id, {
    onDelete: "set null",
  }),
  notes: text("notes"),
  gmailThreadId: varchar("gmail_thread_id", { length: 255 }),
  lastContactDate: timestamp("last_contact_date", { withTimezone: true }),
  clientId: uuid("client_id").references(() => clients.id, { onDelete: "set null" }),
  convertedToEventId: uuid("converted_to_event_id"),
  isReturningClient: boolean("is_returning_client").default(false),
  returningClientSummary: jsonb("returning_client_summary"),
  priorityTag: priorityTagEnum("priority_tag"),
  estimateKeywordsDetected: boolean("estimate_keywords_detected").default(false),
  returningClientChecked: boolean("returning_client_checked").default(false),
  eventCreated: boolean("event_created").default(false),
  linkedEventId: uuid("linked_event_id"),
  depositNumber: varchar("deposit_number", { length: 255 }),
  depositAmount: real("deposit_amount"),
  venue: varchar("venue", { length: 255 }),
  venueMode: venueModeEnum("venue_mode"),
  aiFlagCategory: aiFlagCategoryEnum("ai_flag_category").default(""),
  aiFlagReason: text("ai_flag_reason"),
  skipAutoCall: boolean("skip_auto_call").default(false),
  surveyData: jsonb("survey_data"),
  followupSaleConfirmed: boolean("followup_sale_confirmed"),
  followupClientType: varchar("followup_client_type", { length: 255 }),
  followupResponseEta: timestamp("followup_response_eta", { mode: "date" }),
  followupNextDate: timestamp("followup_next_date", { mode: "date" }),
  followupExperienceConfirmation: text("followup_experience_confirmation"),
  followupWarmthScale: integer("followup_warmth_scale"),
  followupMeetingNotes: text("followup_meeting_notes"),
  followupContractRequired: boolean("followup_contract_required"),
  lostReason: text("lost_reason"),
  lostOkToContact: boolean("lost_ok_to_contact"),
  createdDate: createdDate(),
  updatedDate: updatedDate(),
  createdBy: createdBy(),
});
