export const onboardingStrings = {
  navRecruitment: "Recruitment",
  pageTitle: "Recruitment",
  pageSubtitle: "Hire candidates by role, source, and stage.",
  newCandidate: "New Candidate",
  emptyTitle: "No candidates yet",
  emptyBody: "Add a candidate to start tracking hiring and onboarding.",
  comingSoonTitle: "Onboarding checklist coming soon",
  comingSoonBody:
    "Dave’s workflow packet for this role is not in the tool yet. You can still move this candidate through recruitment stages to Active.",
  filtersRole: "Role",
  filtersSource: "Source",
  filtersHireType: "Hire type",
  filtersAll: "All",
  searchPlaceholder: "Search name or email…",
  resumeUrl: "Resume URL",
  sourceDetail: "Source detail",
  sourceDetailHint: "Referral name, fair name, or other detail",
  declineReason: "Decline reason",
  retainForFuture: "Keep resume for future openings",
  markStepDone: "Mark done",
  markStepPending: "Reopen",
  workflowChecklist: "Onboarding checklist",
  checklistBackfilled:
    "Checklist was missing — it has been generated from the template.",
  credentialsNote:
    "Login details are sent when you begin onboarding. Full CRM access is granted when they are marked active.",
  declineDialogTitle: "Decline candidate",
  declineDialogConfirm: "Confirm decline",
  declineDialogCancel: "Cancel",
  notesTitle: "Notes",
  notesPlaceholder: "Add notes about this candidate…",
  notesSave: "Save notes",
  notesSaved: "Notes saved",
  metaRole: "Role",
  metaHireType: "Hire type",
  metaSource: "Source",
  openResume: "Open resume",
  noResume: "No resume linked",
  scheduleInterviewTitle: "Schedule interview",
  scheduleInterviewSubtitle:
    "Use these shortcuts to reach the candidate, then mark the interview as scheduled.",
  scheduleEmailInvite: "Email interview invite",
  scheduleGoogleMeet: "Open Google Meet",
  scheduleGoogleCalendar: "Add Google Calendar event",
  scheduleCall: "Call candidate",
  scheduleCopyInvite: "Copy invite text",
  scheduleConfirm: "Mark interview scheduled",
  scheduleCancel: "Cancel",
  scheduleNoEmail: "No email on file",
  scheduleNoPhone: "No phone on file",
  scheduleInviteCopied: "Invite text copied",
  needMoreInfoTitle: "Request more information",
  needMoreInfoSubtitle:
    "Select what’s missing, then email or call the candidate. They stay Under Review.",
  needMoreInfoChecklist: "What’s missing?",
  needMoreInfoItemResume: "Updated resume / application materials",
  needMoreInfoItemEligibility: "Work eligibility / employment paperwork",
  needMoreInfoItemAvailability: "Availability / schedule preferences",
  needMoreInfoItemReferences: "References",
  needMoreInfoItemOther: "Other details (they can reply in email)",
  needMoreInfoEmail: "Email document request",
  needMoreInfoCopy: "Copy request text",
  needMoreInfoCall: "Call candidate",
  needMoreInfoResume: "Open resume on file",
  needMoreInfoDone: "Done",
  needMoreInfoCopied: "Request text copied",
  needMoreInfoNoEmail: "No email on file",
  needMoreInfoNoPhone: "No phone on file",
  needMoreInfoNoResume: "No resume linked",
  sendToDaveTitle: "Send to Dave",
  sendToDaveSubtitle:
    "Package availability and interview notes for Dave’s secondary approval, then mark as sent.",
  sendToDaveNotesLabel: "Availability & interview notes",
  sendToDaveNotesPlaceholder:
    "Availability, schedule preferences, and anything Dave should know from the interview…",
  sendToDaveNotesRequired: "Add availability or interview notes before sending",
  sendToDaveEmail: "Email Dave handoff",
  sendToDaveCopy: "Copy handoff text",
  sendToDaveResume: "Open resume on file",
  sendToDaveConfirm: "Mark sent to Dave",
  sendToDaveCancel: "Cancel",
  sendToDaveCopied: "Handoff text copied",
  sendToDaveNoResume: "No resume linked",
  extendOfferTitle: "Extend offer",
  extendOfferSubtitle:
    "Send the offer to the candidate, then mark the offer as extended.",
  extendOfferEmail: "Email offer",
  extendOfferCopy: "Copy offer text",
  extendOfferCall: "Call candidate",
  extendOfferResume: "Open resume on file",
  extendOfferConfirm: "Mark offer extended",
  extendOfferCancel: "Cancel",
  extendOfferCopied: "Offer text copied",
  extendOfferNoEmail: "No email on file",
  extendOfferNoPhone: "No phone on file",
  extendOfferNoResume: "No resume linked",
  offerAcceptedTitle: "Offer accepted",
  offerAcceptedSubtitle:
    "Send a welcome note if you like, then mark the offer as accepted.",
  offerAcceptedEmail: "Email welcome / next steps",
  offerAcceptedCopy: "Copy welcome text",
  offerAcceptedCall: "Call candidate",
  offerAcceptedConfirm: "Mark offer accepted",
  offerAcceptedCancel: "Cancel",
  offerAcceptedCopied: "Welcome text copied",
  offerAcceptedNoEmail: "No email on file",
  offerAcceptedNoPhone: "No phone on file",
  offerDeclinedTitle: "Offer declined",
  offerDeclinedSubtitle:
    "Optionally note why they declined, then mark the candidate withdrawn.",
  offerDeclinedNotesLabel: "Note (optional)",
  offerDeclinedNotesPlaceholder: "Why they declined, or other context…",
  offerDeclinedConfirm: "Mark withdrawn",
  offerDeclinedCancel: "Cancel",
  beginOnboardingTitle: "Begin onboarding",
  beginOnboardingSubtitle:
    "Create their CRM account and email a link to set a password. They get limited onboarding access until marked active.",
  beginOnboardingChecklistHint:
    "After login details are sent, track paperwork and training on this candidate’s onboarding checklist.",
  beginOnboardingEmail: "Email paperwork kickoff (optional)",
  beginOnboardingCopy: "Copy kickoff text",
  beginOnboardingCall: "Call candidate",
  beginOnboardingConfirm: "Send login details",
  beginOnboardingSending: "Sending…",
  beginOnboardingCancel: "Cancel",
  beginOnboardingCopied: "Kickoff text copied",
  beginOnboardingNoEmail: "No email on file",
  beginOnboardingNoPhone: "No phone on file",
  beginOnboardingInviteReady: "Login details sent",
  beginOnboardingInviteEmailSent:
    "An invite email was sent. Share this link if they do not receive it:",
  beginOnboardingInviteManual:
    "Gmail is not connected — share this invite link so they can set a password:",
  beginOnboardingInviteDone: "Done",
  beginOnboardingLinkCopied: "Invite link copied",
  beginOnboardingErrorTitle: "Could not complete onboarding",
  beginOnboardingErrorWithLink:
    "Something went wrong, but you can still share this invite link manually:",
  beginOnboardingLinkLabel: "Invite link (share with the new hire)",
  markActiveTitle: "Mark active employee",
  markActiveSubtitle:
    "Confirm they are ready for independent scheduling. Upgrade their role to full CRM access when appropriate.",
  markActiveConfirm: "Mark active",
  markActiveCancel: "Cancel",
  tabPipeline: "Board",
  tabList: "List",
  tabHireSources: "Hire sources",
  showHired: "Show hired",
  outcomeFilter: "Outcomes",
  outcomeOpen: "In pipeline",
  outcomeDeclined: "Declined",
  outcomeWithdrawn: "Withdrawn",
  outcomeClosed: "Declined & withdrawn",
  listCountLabel: "candidates",
  hireSourcesTitle: "Hire sources & advertising",
  hireSourcesSubtitle:
    "Playbook for every channel — links, contacts, fair dates, and copy you can reuse when posting.",
  hireSourcesBestFor: "Best for",
  hireSourcesHowTo: "How to advertise",
  hireSourcesLinks: "Links",
  hireSourcesContacts: "Contacts",
  hireSourcesEvents: "Upcoming events",
  hireSourcesCopy: "Sample copy",
  hireSourcesCopyBtn: "Copy",
  hireSourcesCopied: "Copied to clipboard",
  hireSourcesNeedsDetail: "Needs detail from Dave",
  hireSourcesTimeline: "Recruitment timeline",
  hireSourcesActiveNow: "Active now",
  hireSourcesRecommended:
    "{source} is the recommended channel right now.",
  hireSourcesAllContacts: "University & career services contacts",
  hireSourcesPrograms: "Academic programs (GMU HTEM)",
  onboardingWelcomeBody:
    "Your onboarding checklist and training materials are being prepared. If you have questions about paperwork or next steps, reach out to the team.",
  onboardingWelcomeContact: "Email info@mangiadc.com",
  onboardingWelcomeLogout: "Logout",
  myOnboardingTitle: "Onboarding",
  myOnboardingWelcome: "Welcome, {name}",
  myOnboardingRole: "Role: {role}",
  myOnboardingLoading: "Loading your onboarding…",
  myOnboardingError: "Could not load onboarding",
  myOnboardingNoRecord:
    "No onboarding record is linked to your account. Contact your manager.",
  myOnboardingTimeline: "Your progress",
  myOnboardingVirtualTraining: "Watch your training videos",
  myOnboardingVirtualTrainingHint:
    "Play each module below. Your progress saves when a video ends.",
  myOnboardingPaperwork: "Paperwork",
  myOnboardingPaperworkHint:
    "Complete these documents with your manager. Status is tracked by the team.",
  myOnboardingVideoWatched: "Watched",
  myOnboardingMarkWatched: "Mark as watched",
  myOnboardingAllVideosWatched:
    "All modules watched. Zach will follow up with a short questionnaire — your manager confirms this step.",
  myOnboardingVideoProgress: "{watched} of {total} modules watched",
  myOnboardingManagerVideoProgress: "{watched}/{total} videos watched by new hire",
  myOnboardingStepPending: "Pending",
  myOnboardingStepDone: "Complete",
  myOnboardingDoThisNow: "Do this now",
  myOnboardingStepOf: "Step {current} of {total} — {label}",
  myOnboardingPaperworkAction:
    "Work through each item. Email HR if you need a form or have a question.",
  myOnboardingPaperworkTitle: "Complete your paperwork",
  myOnboardingPaperworkComplete: "Paperwork complete",
  myOnboardingPaperworkCompleteHint: "Manager confirmed. Training is next.",
  myOnboardingNotifyHr: "Notify HR — paperwork complete",
  myOnboardingEmailAboutDoc: "Email HR",
  myOnboardingOpenForm: "Open form",
  myOnboardingWaitingManager:
    "When you’re done, your manager reviews and unlocks the next step.",
  myOnboardingWhatsNextShadowTitle: "Shadow shifts come next",
  myOnboardingWhatsNextShadow:
    "You’ll shadow an experienced teammate for full events at training pay. Your manager or trainer will schedule shifts — watch your email.",
  myOnboardingWhatsNextEvalTitle: "Evaluation comes next",
  myOnboardingWhatsNextEval:
    "Your trainer submits an evaluation, then management meets with you before independent scheduling.",
  myOnboardingSeeFullChecklist: "Full checklist",
  myOnboardingComingUp: "Coming up later",
  myOnboardingProgress: "{done} of {total} steps complete",
  myOnboardingAllStepsComplete: "You’re all caught up",
  myOnboardingAllStepsCompleteHint:
    "Your manager will reach out about shadow shifts and next steps.",
  myOnboardingLoadingSteps: "Preparing your next step…",
};

export const JOB_ROLES = [
  "Event Support Associate",
  "Event Team Lead",
  "Culinary Instructor",
  "Food Tour Guide",
];

export const HIRE_TYPES = [
  "Practicum",
  "Internship",
  "Part-time",
  "Contractor",
];

export const HIRE_SOURCES = [
  "Indeed",
  "Employee referral",
  "University / career fair",
  "University email blast",
  "Company website",
  "Other",
];

export const CANDIDATE_STAGES = [
  "Application Received",
  "Under Review",
  "Interview Scheduled",
  "Interview Complete",
  "Pending Dave Approval",
  "Offer Extended",
  "Offer Accepted",
  "Onboarding",
  "Active",
  "Declined",
  "Withdrawn",
];

export const ACTIVE_PIPELINE_STAGES = CANDIDATE_STAGES.filter(
  (s) => s !== "Declined" && s !== "Withdrawn"
);

export const STAGE_COLORS = {
  "Application Received": "bg-slate-100 text-slate-800 border-slate-200",
  "Under Review": "bg-blue-100 text-blue-800 border-blue-200",
  "Interview Scheduled": "bg-indigo-100 text-indigo-800 border-indigo-200",
  "Interview Complete": "bg-violet-100 text-violet-800 border-violet-200",
  "Pending Dave Approval": "bg-amber-100 text-amber-900 border-amber-200",
  "Offer Extended": "bg-orange-100 text-orange-900 border-orange-200",
  "Offer Accepted": "bg-emerald-100 text-emerald-800 border-emerald-200",
  Onboarding: "bg-teal-100 text-teal-800 border-teal-200",
  Active: "bg-green-100 text-green-800 border-green-200",
  Declined: "bg-red-100 text-red-800 border-red-200",
  Withdrawn: "bg-gray-100 text-gray-700 border-gray-200",
};
